In [199]:
import numpy as np
print(np.__version__)
np.random.seed(42)  # Tüm modul boyunca sabit kalacak

2.0.2


In [200]:
original = np.array([1,2,3,4,5,6,7,8,9,0])
print(original)
firstSlice = original[:9:2]
print(aSlice, '\n\n')

firstSlice[1] = 100
print(original)


secondSlice =  original[:9:2].copy()
secondSlice[1] = 200
print(original)



print(firstSlice.base is original,'\n')
print(secondSlice.base is original)



[1 2 3 4 5 6 7 8 9 0]
[  1 100   5   7   9] 


[  1   2 100   4   5   6   7   8   9   0]
[  1   2 100   4   5   6   7   8   9   0]
True 

False


In [201]:
indexes = np.array([1,2,3])
print(original[indexes]) #Fancy Indexing
print(original[[1,1,3]])

matris = np.array([[1,2,3,4],[3,4,5,6]])

row = [0,0,0,0]
column = [1,2,1,3]
print(matris[row,column])

[  2 100   4]
[2 2 4]
[2 3 2 4]


In [202]:
number = np.array([1,2,3,4,5,6,7,8,9,0])
results = np.where(number > 5,"büyük","küçük")
print(results)

edited = np.where(number < 5,6,number) #doğru olanları 6 yap, yanlış olanları aynı bırak.
print(edited)

['küçük' 'küçük' 'küçük' 'küçük' 'küçük' 'büyük' 'büyük' 'büyük' 'büyük'
 'küçük']
[6 6 6 6 5 6 7 8 9 6]


In [203]:
array = np.array([1,23,34,67,3])
sorted = np.sort(array)
print(f"sorted: {sorted}\n")
print(f"argsort: {np.argsort(array)}\n") #indexler için

print("array: ",array[np.argsort(array)])


sorted: [ 1  3 23 34 67]

argsort: [0 4 1 2 3]

array:  [ 1  3 23 34 67]


In [204]:
names = np.array(["Greenwood", "Muriqi", "Ederson", "Skriniar"])
ages = np.array([24,32,32,31])

qeue = np.argsort(ages)
print(names[qeue])
print(ages[qeue])

['Greenwood' 'Skriniar' 'Muriqi' 'Ederson']
[24 31 32 32]


In [205]:
oneArray = np.array([1,2,3,4,5,6,7,8,9,0,0,1,2,54,9])
print(np.unique(oneArray)) #tekilleştirir


degerler, sayilar = np.unique(oneArray, return_counts=True)
print("Değerler:", degerler)
print("Sayılar :", sayilar)

[ 0  1  2  3  4  5  6  7  8  9 54]
Değerler: [ 0  1  2  3  4  5  6  7  8  9 54]
Sayılar : [2 2 2 1 1 1 1 1 1 2 1]


In [206]:
print(oneArray, '\n')


array = np.concatenate((array, np.array(list(set(oneArray) - set(array))))) # Using np.concatenate function and converting set difference to an array of elements
print(array, '\n')

print(np.concatenate([oneArray, array]), '\n') #arrayleri uç uca ekler.
print(np.vstack([oneArray[:len(array)], array]), '\n') #arrayleri üst üste ekleyip matris oluşturur.
print( np.hstack([oneArray, array]), '\n') #arrayleri yan yana ekler.

[ 1  2  3  4  5  6  7  8  9  0  0  1  2 54  9] 

[ 1 23 34 67  3  0  2  4  5  6  7  8  9 54] 

[ 1  2  3  4  5  6  7  8  9  0  0  1  2 54  9  1 23 34 67  3  0  2  4  5
  6  7  8  9 54] 

[[ 1  2  3  4  5  6  7  8  9  0  0  1  2 54]
 [ 1 23 34 67  3  0  2  4  5  6  7  8  9 54]] 

[ 1  2  3  4  5  6  7  8  9  0  0  1  2 54  9  1 23 34 67  3  0  2  4  5
  6  7  8  9 54] 



In [207]:
firstMatris = np.array([[1,2,3,4,5],[6,7,8,9,0]])
secondMatris = np.array([[11,22,33,44,55],[66,77,88,99,0]])
thirdMatris = np.array([[111,222,333,444,555]])

print(np.vstack([firstMatris, secondMatris, thirdMatris]), '\n') # alt alta ekleme yapar.
print(np.hstack([firstMatris, secondMatris]), '\n') #sağına ekleme yapar, satır sayısına dikkat edilmeli.




[[  1   2   3   4   5]
 [  6   7   8   9   0]
 [ 11  22  33  44  55]
 [ 66  77  88  99   0]
 [111 222 333 444 555]] 

[[ 1  2  3  4  5 11 22 33 44 55]
 [ 6  7  8  9  0 66 77 88 99  0]] 



In [208]:
tmp = np.split(oneArray,3) # 3 parçaya böler
print(tmp)

for i,piece in enumerate(tmp):  #enumerate parçaların indexleriyle birlikte dolaşmasını sağlar.
  print(f"{i}. parça: {piece}.")

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 0]), array([ 0,  1,  2, 54,  9])]
0. parça: [1 2 3 4 5].
1. parça: [6 7 8 9 0].
2. parça: [ 0  1  2 54  9].


In [209]:
matris = np.concatenate([matris, matris])
print(matris,'\n\n')

print(matris.sum(axis=0)) #dikey olarak toplar
print(matris.sum(axis=1)) #yatay olarak toplar
print(matris.sum()) #tek bir sayıya toplar

[[1 2 3 4]
 [3 4 5 6]
 [1 2 3 4]
 [3 4 5 6]] 


[ 8 12 16 20]
[10 18 10 18]
56


In [210]:
cub = np.arange(24).reshape(2, 3, 4)
print(cub,'\n\n')

print("axis=0 ile toplam şekli:", cub.sum(axis=0).shape)
print("axis=1 ile toplam şekli:", cub.sum(axis=1).shape)
print("axis=2 ile toplam şekli:", cub.sum(axis=2).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 


axis=0 ile toplam şekli: (3, 4)
axis=1 ile toplam şekli: (2, 4)
axis=2 ile toplam şekli: (2, 3)


In [211]:
import time as t

n = 1_000_000
liste = list(range(n)) # 1 milyon elemanlı Python listesi
array = np.arange(n)   # 1 milyon elemanlı array

start = t.time() #süreyi başlattık
liste_kareler = [x ** 2 for x in liste]  #tüm elemanların karesini alma
python_suresi = time.time() - start  #süre hesaplaması

start = t.time() #süreyi başlattık
array_kareler = array ** 2                    # tüm elemanların karesini TEK SATIRDA, döngüsüz alıyoruz
numpy_suresi = time.time() - start

print(f"Python süresi: {python_suresi}")
print(f"NumPy süresi: {numpy_suresi}")
print(f"Fark : {python_suresi-numpy_suresi}")


Python süresi: 0.08756089210510254
NumPy süresi: 0.002183675765991211
Fark : 0.08537721633911133


In [212]:
array = ([np.pi, 1,2,4,5])
#her eleman için ilgili matematiksel işlemler uygulanır.
print(np.sin(array))
print(np.cos(array))
print(np.tan(array))
print(np.exp(array))

[ 1.22464680e-16  8.41470985e-01  9.09297427e-01 -7.56802495e-01
 -9.58924275e-01]
[-1.          0.54030231 -0.41614684 -0.65364362  0.28366219]
[-1.22464680e-16  1.55740772e+00 -2.18503986e+00  1.15782128e+00
 -3.38051501e+00]
[ 23.14069263   2.71828183   7.3890561   54.59815003 148.4131591 ]


In [213]:
def own_func(x):
  return x**x

print(vectorize_funk(array), '\n')
vectorize_funk = np.vectorize(own_func) #vectorize yazdığımız fonsiyonu her bir eleman için kullanılabilir hale getirir.
print(vectorize_funk(array))

[3.64621596e+01 1.00000000e+00 4.00000000e+00 2.56000000e+02
 3.12500000e+03] 

[3.64621596e+01 1.00000000e+00 4.00000000e+00 2.56000000e+02
 3.12500000e+03]


In [214]:
data_type = np.dtype([("name","U10"),("yas","i4"),("boy","f4")])
# U10 -> en fazla 10 karakterlik unicode string, i4 -> 4 byte'lık integer, f4 -> 4 byte'lık float
persons = np.array([("Greenwood",24,180),("Ederson",32,187),("Skriniar",32,186)],dtype=data_type)
print(persons)
print(persons["name"])
print(persons["yas"])
print(persons["boy"])



[('Greenwood', 24, 180.) ('Ederson', 32, 187.) ('Skriniar', 32, 186.)]
['Greenwood' 'Ederson' 'Skriniar']
[24 32 32]
[180. 187. 186.]


In [215]:
ozdegerler, ozvektorler = np.linalg.eig(matris)# Özdeğer (eigenvalue) ve özvektörleri (eigenvector) hesaplanır.
print("Özdeğerler:", ozdegerler)
print("Özvektorler:\n", ozvektorler)


A = np.array([[3, 1],
              [1, 2]])
b = np.array([9, 8])
result = np.linalg.solve(A, b)   # denklem sistemini çözer (matris tersini almaktan daha kararlı ve hızlıdır).

print(result)

Özdeğerler: [ 1.45498344e+01 -5.49834435e-01 -1.69812267e-15 -3.70038204e-16]
Özvektorler:
 [[-0.34957176 -0.56343123  0.42174136  0.31014159]
 [-0.61465404  0.42725314 -0.82280665 -0.07702696]
 [-0.34957176 -0.56343123  0.38038921 -0.77637086]
 [-0.61465404  0.42725314  0.02067608  0.54325623]]
[2. 3.]


In [216]:
np.save("array.npy", A) #kaydetmeyi sağlar.
loaded = np.load("array.npy") #yükler.
print(np.array_equal(A, loaded)) #true olmalı

np.savez("arrays.npz",first=A,second=b) #çoklu kayır için kullanılır. .npz dikkat.
loaded2= np.load("arrays.npz")
print(loaded2["first"])
print(loaded2["second"])


True
[[3 1]
 [1 2]]
[9 8]


In [230]:
temps = np.arange(100)
temps = np.concatenate((temps, [np.nan, np.nan]))
print(temps)

nulls = np.isnan(temps)
print(nulls.sum())

acceptable = (temps > 20) & (temps < 80) & (~np.isnan(temps))
print("acceptable:  ",temps[acceptable])
print("mean of acceptable:  ",temps[acceptable].mean())

print(acceptable.size)
print("Trash values: ", temps.size-temps[acceptable].size)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99. nan nan]
2
acceptable:   [21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38.
 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54. 55. 56.
 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72. 73. 74.
 75. 76. 77. 78. 79.]
mean of acceptable:   50.0
102
Trash values:  43
