In [2]:
import numpy as np
print(f"Version: {np.__version__}")


Version: 2.0.2


In [3]:
list1 = [1,2,3]
array1 = np.array(list1)

print(f'Type: {type(array1)}')

Type: <class 'numpy.ndarray'>


In [4]:
matris = np.array([[1,2,3],[4,5,6]])
print(matris)
print(f"Dimension of matris: {matris.ndim}.")

[[1 2 3]
 [4 5 6]]
Dimension of matris: 2.


In [5]:
print("shape :", matris.shape)
print("ndim  :", matris.ndim)
print("size  :", matris.size)
print("dtype :", matris.dtype)
print("itemsize:", matris.itemsize, "byte")

shape : (2, 3)
ndim  : 2
size  : 6
dtype : int64
itemsize: 8 byte


In [6]:
zeros = np.zeros((2,3))
print(zeros , '\n')

ones = np.ones((2,3))
print(ones , '\n')

full = np.full((2,3), 5)
print(full, '\n')

eye = np.eye(3) #3x3
print(eye, '\n')

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[5 5 5]
 [5 5 5]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [7]:
print(array1[1])
print(array1[1:3])
print(array1[-1])
print(array1[::2])

2
[2 3]
3
[1 3]


In [10]:
print(matris[1,2])
print(matris[:,1])
print(matris[1,:])

6
[2 5]
[4 5 6]


In [16]:
condition = array1 > 1
print(condition)

print(array1[condition]) #only true

print(array1[array1 >= 1])

[False  True  True]
[2 3]
[1 2 3]


In [28]:
array2 = np.arange(12)
print(array2, '\n\n')

array3 = array2.reshape(3,4)
print(array3, '\n\n')

print(array2.reshape(2,3,2), '\n\n')

print(array3.T, '\n\n')

print(array3.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11] 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
arrayA = np.array([[1,2,3],[4,5,6]])
arrayB = np.array([[7,8,9],[10,11,12]])

print("Toplama   :", arrayA + arrayB)
print("Çıkarma   :", arrayA - arrayB)
print("Çarpma    :", arrayA * arrayB)
print("Bölme     :", arrayA / arrayB)
print("Üs alma   :", arrayA ** arrayB)

Toplama   : [[ 8 10 12]
 [14 16 18]]
Çıkarma   : [[-6 -6 -6]
 [-6 -6 -6]]
Çarpma    : [[ 7 16 27]
 [40 55 72]]
Bölme     : [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
Üs alma   : [[         1        256      19683]
 [   1048576   48828125 2176782336]]


In [33]:
matrisA = np.array([[1,2,3],[4,5,6]])
arrayC = np.array([100,200,300])

print(matrisA + arrayC, '\n\n')

print(arrayC * 5, '\n\n')

print(matrisA + 5, '\n\n')


[[101 202 303]
 [104 205 306]] 


[ 500 1000 1500] 


[[ 6  7  8]
 [ 9 10 11]] 




In [37]:
print(arrayC.sum()) #toplam
print(arrayC.mean()) #ortalama
print(arrayC.max()) #maximum değer
print(arrayC.min()) #minimum değer
print(arrayC.std()) #standart sapma
print(arrayC.var()) #varyans

print(matrisA.sum(axis=0)) #sütun toplamları
print(matrisA.sum(axis=1)) #satır toplamları

600
200.0
300
100
81.64965809277261
6666.666666666667
[5 7 9]
[ 6 15]


In [47]:
np.random.seed(42) #tekrar çalıştırdığımızda sayılar değşmez

rastgele_array = np.random.rand(3, 3)      # 0 ile 1 arasında, 3x3 boyutunda rastgele ondalıklı sayılar üretir
print("rand:\n", rastgele_array)


tam_sayilar = np.random.randint(1, 100, size=5)  # 1 (dahil) ile 100 (hariç) arasında 5 rastgele tam sayı üretir
print("randint:", tam_sayilar)

normal_dagilim = np.random.randn(4)   # standart normal dağılımdan (ortalama 0, std 1) 4 sayı üretir
print("randn:", normal_dagilim)

rand:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
randint: [24  3 22 53  2]
randn: [0.23309524 0.11799461 1.46237812 1.53871497]


In [53]:
firstMatris = np.array([[1,2],[4,5]])
secondMatris = np.array([[7,8],[10,11]])

matrisMult = firstMatris @ secondMatris #Matris çarpımı
print(matrisMult, '\n\n')


determinant = np.linalg.det(firstMatris) #Determinant hesaplar
print(determinant, '\n\n')

inverse = np.linalg.inv(firstMatris) #Tersini alır
print(inverse, '\n\n')

print(firstMatris.T) #Transpose

[[27 30]
 [78 87]] 


-2.9999999999999996 


[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]] 


[[1 4]
 [2 5]]
